// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK7u-lpKQrWP5VaplIyItDhzuhzABZxlI',
    appId: '1:847871911666:web:61e2fb989e0ebe2052d26b',
    messagingSenderId: '847871911666',
    projectId: 'blinkitclone-588ad',
    authDomain: 'blinkitclone-588ad.firebaseapp.com',
    storageBucket: 'blinkitclone-588ad.firebasestorage.app',
    measurementId: 'G-F3YL6QXP14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLDePbpuwLAxEuv7PoVHO21fFQ6B9aEQA',
    appId: '1:847871911666:android:e0ad987200d9110352d26b',
    messagingSenderId: '847871911666',
    projectId: 'blinkitclone-588ad',
    storageBucket: 'blinkitclone-588ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuSZPpQIiJenHEFqWIDDfVzqJ_7uol0k',
    appId: '1:847871911666:ios:e2a99afed2b0d8c452d26b',
    messagingSenderId: '847871911666',
    projectId: 'blinkitclone-588ad',
    storageBucket: 'blinkitclone-588ad.firebasestorage.app',
    iosClientId: '847871911666-s5u03sqe4g375mltfcc0i0o8e8ao9jao.apps.googleusercontent.com',
    iosBundleId: 'com.example.blinkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuSZPpQIiJenHEFqWIDDfVzqJ_7uol0k',
    appId: '1:847871911666:ios:e2a99afed2b0d8c452d26b',
    messagingSenderId: '847871911666',
    projectId: 'blinkitclone-588ad',
    storageBucket: 'blinkitclone-588ad.firebasestorage.app',
    iosClientId: '847871911666-s5u03sqe4g375mltfcc0i0o8e8ao9jao.apps.googleusercontent.com',
    iosBundleId: 'com.example.blinkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK7u-lpKQrWP5VaplIyItDhzuhzABZxlI',
    appId: '1:847871911666:web:358f44f6c51f102f52d26b',
    messagingSenderId: '847871911666',
    projectId: 'blinkitclone-588ad',
    authDomain: 'blinkitclone-588ad.firebaseapp.com',
    storageBucket: 'blinkitclone-588ad.firebasestorage.app',
    measurementId: 'G-NKWYV6E0RZ',
  );
}
